import re
from datetime import datetime
from pathlib import Path

import anthropic
from dotenv import load_dotenv

load_dotenv()

PROMPT_TEMPLATE = """\
You are an expert sales intelligence researcher. Generate a thorough pre-call intelligence brief for the following company.

Company: {company_name}

Structure your response as a markdown document with exactly these seven sections:

## 1. Company Overview
What the company does, estimated size (employees/revenue if known), industry vertical, and headquarters location.

## 2. Recent News & Developments
Key developments from the last 6 months: funding rounds, product launches, leadership changes, partnerships, acquisitions, or press coverage.

## 3. Likely Tech Stack & Infrastructure
Based on the company's industry, size, and any public signals (job postings, engineering blog, open-source presence), what technologies are they likely using? Include categories: cloud provider, languages/frameworks, data infrastructure, DevOps/CI-CD, and any known SaaS tools.

## 4. Key Business Challenges / Pain Points
What operational, technical, or strategic problems is this type of company likely facing right now? Be specific to their industry and growth stage.

## 5. Potential Decision Makers
List the typical titles and roles that would be relevant buyers or influencers for a B2B sale. Include both technical and business-side stakeholders.

## 6. Suggested Talking Points & Opening Angle
Concrete, specific talking points tailored to this company. What problem should you lead with? What outcome should you promise? Suggest an opening line or email subject.

## 7. Red Flags or Risks
Any signs that this account could be a poor fit, a long sales cycle, budget-constrained, or otherwise risky to pursue. Include competitor relationships if relevant.
"""


def run(company_name: str, output_dir: Path) -> Path:
    client = anthropic.Anthropic()

    prompt = PROMPT_TEMPLATE.format(company_name=company_name)

    with client.messages.stream(
        model="claude-opus-4-6",
        max_tokens=4096,
        thinking={"type": "adaptive"},
        messages=[{"role": "user", "content": prompt}],
    ) as stream:
        response = stream.get_final_message()

    brief_text = next(
        block.text for block in response.content if block.type == "text"
    )

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    safe_name = re.sub(r'[^\w\s-]', '', company_name).strip().replace(' ', '_')
    output_path = output_dir / f"{safe_name}_brief.md"

    header = (
        f"<!-- Generated by AI Integrator Lab — Account Intelligence Briefer -->\n"
        f"<!-- Timestamp: {timestamp} -->\n"
        f"<!-- Note: This brief is AI-generated and should be verified before use. -->\n\n"
        f"# Account Intelligence Brief: {company_name}\n\n"
        f"*Generated: {timestamp}*\n\n---\n\n"
    )

    output_path.write_text(header + brief_text, encoding="utf-8")

    return output_path
